.DEFAULT_GOAL := help

MAKEFILES_DIR := makefiles

include $(MAKEFILES_DIR)/common.mk
include $(MAKEFILES_DIR)/runtime.mk
include $(MAKEFILES_DIR)/build.mk
include $(MAKEFILES_DIR)/release.mk
include $(MAKEFILES_DIR)/install.mk
include $(MAKEFILES_DIR)/deploy.mk
include $(MAKEFILES_DIR)/local-e2e.mk

export GO RELEASE_DIR
export BIN_DIR TUNNEL_PKG RELAY_PKG MIGRATOR_PKG
export TUNNEL_BIN RELAY_BUILD_BIN MIGRATOR_BUILD_BIN
export INSTALL_DIR
export RELAY_PORT RELAY_BIN RELAY_PID_FILE RELAY_LOG_FILE
export LOG_DIR
export LOCAL_E2E_PG_SCRIPT LOCAL_E2E_RUNNER_SCRIPT
export LOCAL_E2E_PG_IMAGE LOCAL_E2E_PG_CONTAINER LOCAL_E2E_PG_VOLUME LOCAL_E2E_PG_PORT LOCAL_E2E_PG_HOST LOCAL_E2E_PG_USER LOCAL_E2E_PG_PASSWORD LOCAL_E2E_PG_DATABASE LOCAL_E2E_PG_READY_TIMEOUT LOCAL_E2E_OUTPUT_FILE
export WEBSITE_REPO_DIR WEBSITE_BUILD_DIR DEPLOY_WEBSITE_ROOT DEPLOY_WEBSITE_TMP_DIR
export ANSIBLE ANSIBLE_CONFIG ANSIBLE_PROJECT_ROOT ANSIBLE_INVENTORY ANSIBLE_PLAYBOOK ANSIBLE_EXTRA_VARS_FILE ANSIBLE_WEBSITE_REPO_DIR ANSIBLE_TAGS ANSIBLE_DRY_RUN
